# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b8d09a1a0b5b74442829f5c617084a1fd7f9ba86db617eb256f037f3ca1f1a821e7a7a47410aee67ce37268d6ea3ec43321547bfae7ba61ffc3413063059ae5

test:
  secret_key_base: 6ce6ae47a7381d399ae759452d7782d772009ecbeec7dddc79f9b39ab683dbb6df33c327f7098a5f6d1e2393e47413df352a732dd8a345b39a9e3a463896601f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
